# -*- coding: utf-8 -*-
"""Scraping Financial data .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QxE1qC7lv3j6tDdteA0qiLNwsTKPQ93V

Web Scraping Project
"""

#import libraries

import pandas as pd
import datetime

#Webscrap S&P 500 companies using Wikepdia

Webpage = pd.read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')

#explore the scrapped information

type(Webpage)

len(Webpage)

Webpage[0]

#store the table as a dataframe

company_df = Webpage[0]

#Explore dataframe

company_df.info()

company_df.describe()

company_df['Symbol'].unique()

company_df['GICS Sector'].unique()

# creating a separate dataframe where energy is the sector

Energy= company_df[(company_df['GICS Sector']== 'Energy')]

"""Utilize yfinance to download stock prices from Yahoo Finance

"""

import yfinance as yf

start_date = datetime.datetime(2021,1,25)
end_date = datetime.datetime.today()

print(start_date)
print(end_date)

stock_price = pd.DataFrame()

df = yf.download('APA', start = start_date, end = end_date)

#use for loops to download stock price for each symbol in the energy sector
for ticker in Energy['Symbol'].unique():
    df = yf.download(ticker, start=start_date, end=end_date)
    df['Symbol'] = ticker

    # Concatenate the current DataFrame to the stock_price DataFrame
    stock_price = pd.concat([stock_price, df])
    print(df.head())

APA= stock_price[(stock_price['Symbol'] == 'APA')]

"""Data Visualization

"""

import plotly.graph_objects as go
import pandas as pd

df = APA

fig= go.Figure(data=[go.Candlestick(x=df.index,
                                    open=df['Open'], high=df['High'],
                                    low=df['Low'], close=df['Close'])
                                        ])
fig.show()

Cleaned= stock_price.reset_index()
print(Cleaned)

Cleaned.to_csv('stock_price export.csv', index= False)